
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nextflow-rw-many
spec:
  storageClassName: nfs-storage
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi

---

apiVersion: v1
kind: Pod
metadata:
  name: nextflow
spec:
  serviceAccountName: nextflow
  volumes:
    - name: nf-pvc
      persistentVolumeClaim:
        claimName: nextflow-rw-many
  containers:
    - name: nextflow
      image: nextflow/nextflow:24.10.2
      command: ["sleep"]
      args: ["1000"]
      volumeMounts:
        - mountPath: "/workspace"
          name: nf-pvc
