apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pod-creator
rules:
- apiGroups: [""]
  resources: ["pods", "pods/status", "pods/log", "secrets"]
  verbs: ["create", "get", "watch", "list", "update", "patch", "delete"]
