
apiVersion: v1
kind: Pod
metadata:
  name: snakemake
spec:
  serviceAccountName: nextflow
  containers:
    - name: nextflow
      image: snakemake/snakemake:v8.25.5
      command: ["sleep"]
      args: ["1000"]
